version: "3.8"
services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=mongodb://mongodb:27017/dynamikdb?retryWrites=true&w=majority
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/dynamikdb?retryWrites=true&w=majority
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
